### ISSUE TITLE
Customizable claimlist command

### ISSUE THREAD

**Issue by panchalf** [NotRyken/ClaimPoints#2]
### Request Description

The server I'm playing on only has claimslist enabled for players instead of claimlist, so it would be nice to have the command customizable through the config menu

**Comment by NotRyken** [comment]
Do you require this for a version pre-1.21?

**Comment by panchalf** [comment]
yes, on 1.20.6

**Comment by NotRyken** [comment]
Added in v2.0.0 and for 1.20.6 in [v0.1.1](https://github.com/TerminalMC/ClaimPoints/releases/tag/v0.1.1)
